services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: UsersAPI
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - user_network

  users-api:
    build: .
    volumes:
      - log_data:/var/logs/spring-boot/
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/UsersAPI
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    ports:
      - 8080:8080
    networks:
      - user_network

networks:
  user_network:
    driver: bridge


volumes:
  postgres_data:
  log_data: