spring:
  application:
    name: Users API
  datasource:
    url: jdbc:postgresql://localhost:5432/UsersAPI
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-main.yml
    default-schema: public
springdoc:
  api-docs:
    path: /api/v1
  swagger-ui:
    path: /api/v1/doc

logging:
  level:
    org.springframework: INFO
    com.user.subscriptions: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
